Type: AWS::S3::Bucket
Properties:
  BucketName: ${self:provider.environment.BUCKET}
  AccessControl: PublicRead
  CorsConfiguration:
    CorsRules:
      - AllowedOrigins:
          - '*'
        AllowedMethods:
          - POST
          - GET
          - PUT
          - DELETE
          - HEAD
        AllowedHeaders:
          - '*'
